# Generated by Django 4.2 on 2023-09-04 12:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tournament', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doubleeliminationmatches',
            name='player1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='DoubleEliminationPlayer1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='doubleeliminationmatches',
            name='player2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='DoubleEliminationPlayer2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='singleeliminationmatches',
            name='player1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='SingleEliminationPlayer1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='singleeliminationmatches',
            name='player2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='SingleEliminationPlayer2', to=settings.AUTH_USER_MODEL),
        ),
    ]
