# Generated by Django 4.2 on 2023-09-05 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0004_doubleeliminationmatches_pwinner'),
    ]

    operations = [
        migrations.CreateModel(
            name='TournamentPrizePool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placement', models.CharField(blank=True, max_length=500, null=True)),
                ('prize', models.IntegerField(default=0)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournament_prize_pools', to='tournament.tournament')),
            ],
        ),
    ]
