# Generated by Django 4.2 on 2023-09-07 09:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tournament', '0006_alter_doubleeliminationmatches_round_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage',
            name='stage_date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='BattleRoyalMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pWinner1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='BattleRoyalePlayerWinner1', to=settings.AUTH_USER_MODEL)),
                ('pWinner2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='BattleRoyalePlayerWinner2', to=settings.AUTH_USER_MODEL)),
                ('pWinner3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='BattleRoyalePlayerWinner3', to=settings.AUTH_USER_MODEL)),
                ('players', models.ManyToManyField(blank=True, related_name='BattleRoyalePlayer', to=settings.AUTH_USER_MODEL)),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battle_royale_stage', to='tournament.stage')),
                ('teams', models.ManyToManyField(blank=True, related_name='BattleRoyaleTeam', to='tournament.team')),
                ('winner1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='BattleRoyaleTeamWinner1', to='tournament.team')),
                ('winner2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='BattleRoyaleTeamWinner2', to='tournament.team')),
                ('winner3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='BattleRoyaleTeamWinner3', to='tournament.team')),
            ],
        ),
    ]
