# Generated by Django 4.2 on 2023-09-07 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0007_stage_stage_date_time_battleroyalmatch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battleroyalmatch',
            name='stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='battle_royale_stage', to='tournament.stage'),
        ),
    ]
