# Generated by Django 4.2 on 2023-09-08 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0008_alter_battleroyalmatch_stage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stage',
            name='stage_date_time',
        ),
        migrations.AddField(
            model_name='battleroyalmatch',
            name='stage_date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
