# Generated by Django 4.2 on 2023-09-15 04:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tournament', '0009_remove_stage_stage_date_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='battleroyalmatch',
            old_name='stage_date_time',
            new_name='start_date_time',
        ),
        migrations.RemoveField(
            model_name='battleroyalmatch',
            name='pWinner1',
        ),
        migrations.RemoveField(
            model_name='battleroyalmatch',
            name='pWinner2',
        ),
        migrations.RemoveField(
            model_name='battleroyalmatch',
            name='pWinner3',
        ),
        migrations.RemoveField(
            model_name='battleroyalmatch',
            name='players',
        ),
        migrations.RemoveField(
            model_name='battleroyalmatch',
            name='teams',
        ),
        migrations.RemoveField(
            model_name='battleroyalmatch',
            name='winner1',
        ),
        migrations.RemoveField(
            model_name='battleroyalmatch',
            name='winner2',
        ),
        migrations.RemoveField(
            model_name='battleroyalmatch',
            name='winner3',
        ),
        migrations.CreateModel(
            name='BattleRoyalTeamDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placement', models.IntegerField(blank=True, null=True)),
                ('killPoints', models.IntegerField(blank=True, null=True)),
                ('point', models.IntegerField(blank=True, null=True)),
                ('battleRoyale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='battle_royale_team', to='tournament.battleroyalmatch')),
                ('team', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='BattleRoyaleTeam', to='tournament.team')),
            ],
        ),
        migrations.CreateModel(
            name='BattleRoyalPlayerDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placement', models.IntegerField(blank=True, null=True)),
                ('killPoints', models.IntegerField(blank=True, null=True)),
                ('point', models.IntegerField(blank=True, null=True)),
                ('battleRoyale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='battle_royale_player', to='tournament.battleroyalmatch')),
                ('players', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='BattleRoyalePlayer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
