# Generated by Django 4.2 on 2024-03-10 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0010_rename_stage_date_time_battleroyalmatch_start_date_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eliminationmode',
            name='elimination_mode',
            field=models.CharField(choices=[('Single Elimination', 'Single Elimination'), ('Double Elimination', 'Double Elimination'), ('Battle Royale', 'Battle Royale'), ('Round Robin', 'Round Robin')], max_length=500),
        ),
    ]
