# Generated by Django 4.2 on 2023-06-20 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0017_alter_event_is_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamtournamentregistration',
            name='payment_method',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Bank Transfer', 'Bank Transfer'), ('Esewa', 'Esewa'), ('Khalti', 'Khalti'), ('Other', 'Other')], default='Other', max_length=500),
        ),
    ]
