# Generated by Django 4.2 on 2023-06-20 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0018_alter_teamtournamentregistration_payment_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teamtournamentregistration',
            name='registration_fee',
        ),
    ]
