from django.contrib import admin
from .models import *
admin.site.register(Tournament)
admin.site.register(EliminationMode)
admin.site.register(Game)
admin.site.register(Event)
admin.site.register(Team)
admin.site.register(SoloTournamentRegistration)
admin.site.register(TeamTournamentRegistration)
admin.site.register(TournamentSponsor)
admin.site.register(EventSponsor)
admin.site.register(TournamentFAQ)
admin.site.register(EventFAQ)
admin.site.register(Stage)
admin.site.register(SoloMatch)
admin.site.register(TeamMatch)
admin.site.register(SingleEliminationMatches)
admin.site.register(SingleEliminationRound)
admin.site.register(DoubleEliminationMatches)
admin.site.register(DoubleEliminationRound)
admin.site.register(TournamentPrizePool)
admin.site.register(BattleRoyalMatch)
admin.site.register(BattleRoyalTeamDetails)
admin.site.register(BattleRoyalPlayerDetails)

