from django.urls import path
from . import tournament_views

urlpatterns = [
    path('event-tournaments/', tournament_views.event_tournaments_list, name='event_tournaments_list'),
    path('create-tournament/', tournament_views.create_tournament, name='create_tournament'),
    path('tournaments/', tournament_views.tournaments_list, name='tournaments'),
    path('get-tournament-detail/', tournament_views.tournament_details, name='tournament_details'),
    path('tournament-detail/<int:id>/', tournament_views.tournament_detail, name='tournament_detail'),
    path('update-tournament/', tournament_views.update_tournament, name='update_tournament'),
    path('delete-tournament/', tournament_views.delete_tournament, name='delete_tournament'),
    path('publish-tournament/', tournament_views.open_tournament_registration, name='open_tournament_registration'),
    path('registered-teams/', tournament_views.registered_teams, name='registered_teams'),
    path('register-team-initials/', tournament_views.register_team_initials, name='register_team_initials'),
    path('register-team/', tournament_views.register_team, name='register_team'),
    path('create-tournament-sponsor/', tournament_views.create_tournament_sponsor, name='create_tournament_sponsor'),
    path('get-tournament-sponsors/', tournament_views.get_tournament_sponsor, name='tournament_sponsor'),
    path('get-tournament-sponsors-list/', tournament_views.get_tournament_sponsor_list, name='tournament_sponsor_list'),
    path('update-tournament-sponsor/', tournament_views.update_tournament_sponsor, name='update_tournament_sponsor'),
    path('delete-tournament-sponsor/', tournament_views.delete_tournament_sponsor, name='delete_tournament_sponsor'),
    path('create-tournament-faq/', tournament_views.create_tournament_faq, name='create_tournament_faq'),
    path('get-tournament-faqs-list/', tournament_views.get_tournament_faq_list, name='tournament_faq_list'),
    path('get-tournament-faq/', tournament_views.get_tournament_faq, name='tournament_faq'),
    path('update-tournament-faq/', tournament_views.update_tournament_faq, name='update_tournament_faq'),
    path('delete-tournament-faq/', tournament_views.delete_tournament_faq, name='delete_tournament_faq'),
    path('create-tournament-stream/', tournament_views.create_tournament_stream, name='create_tournament_stream'),
    path('get-tournament-stream-list/', tournament_views.get_tournament_stream_list, name='tournament_stream_list'),
    path('get-tournament-stream/', tournament_views.get_tournament_stream, name='tournament_stream'),
    path('update-tournament-stream/', tournament_views.update_tournament_stream, name='update_tournament_stream'),
    path('delete-tournament-stream/', tournament_views.delete_tournament_stream, name='delete_tournament_stream'),
    path('create-tournament-stage/', tournament_views.create_stage, name='create_stage'),
    path('get-tournament-stage-list/', tournament_views.get_stage_list, name='stage_list'),
    path('get-tournament-stage/', tournament_views.get_stage, name='stage'),
    path('update-tournament-stage/', tournament_views.update_stage, name='update_stage'),
    path('delete-tournament-stage/', tournament_views.delete_stage, name='delete_stage'),
]
