# from django import views
# from django.urls import path
# from .views import (
#     bannerimage_create,
#     bannerimage_delete,
#     bannerimage_update,
#     create_tournament,
#     delete_tournament,
#     prizepool_create,
#     prizepool_delete,
#     prizepool_detail,
#     prizepool_list,
#     prizepool_update,
#     sponsor_list,
#     sponsor_detail,
#     tournament_bracket_detail,
#     tournament_bracket_list,
#     tournament_detail,
#     create_registration,
#     tournament_list,
#     update_registration,
#     delete_registration,
#     create_participant,
#     delete_participant,
#     match_detail,
#     create_match,
#     update_match,
#     delete_match,
#     livepage_detail,
#     update_livepage,
#     announcement_detail,
#     create_announcement,
# )

# urlpatterns = [
#     path('sponsors/', sponsor_list, name='sponsor_list'),
#     path('sponsors/<int:pk>/', sponsor_detail, name='sponsor_detail'),
#     path('tournaments/', create_tournament, name = 'create_tournament'),
#     path('tournaments/<int:pk>/delete/', delete_tournament, name='delete_tournament'),
#     path('tournament_list/', tournament_list, name='tournament_list'),
#     path('tournaments/<int:pk>/', tournament_detail, name='tournament_detail'),
#     path('bannerimage/create/', bannerimage_create, name='banner_image_create'),
#     path('bannerimage/<int:pk>/update/', bannerimage_update, name='banner_image_update'),
#     path('bannerimage/<int:pk>/delete/', bannerimage_delete, name='banner_image_delete'),
#     path('prizepool/', prizepool_list, name='prize_pool_list'),
#     path('prizepool/create/', prizepool_create, name='prize_pool_create'),
#     path('prizepool/<int:pk>/', prizepool_detail, name='prize_pool_detail'),
#     path('prizepool/<int:pk>/update/', prizepool_update, name='prize_pool_update'),
#     path('prizepool/<int:pk>/delete/', prizepool_delete, name='prize_pool_delete'),
#     path('registrations/', create_registration, name='create_registration'),
#     path('registrations/<int:pk>/', update_registration, name='update_registration'),
#     path('registrations/<int:pk>/delete/', delete_registration, name='delete_registration'),
#     path('participants/', create_participant, name='create_participant'),
#     path('participants/<int:pk>/delete/', delete_participant, name='delete_participant'),
#     path('matches/<int:pk>/', match_detail, name='match_detail'),
#     path('matches/', create_match, name='create_match'),
#     path('matches/<int:pk>/update/', update_match, name='update_match'),
#     path('matches/<int:pk>/delete/', delete_match, name='delete_match'),
#     path('tournament-brackets/', tournament_bracket_list, name='tournament_bracket_list'),
#     path('tournament-brackets/<int:pk>/',tournament_bracket_detail, name='tournament_bracket_detail'),
#     path('livepages/<int:pk>/', livepage_detail, name='livepage_detail'),
#     path('livepages/<int:pk>/update/', update_livepage, name='update_livepage'),
#     path('announcements/<int:pk>/', announcement_detail, name='announcement_detail'),
#     path('announcements/', create_announcement, name='create_announcement'),
# ]
